### ISSUE TITLE
WindowsError: [Error 126] The specified module could not be found

### ISSUE THREAD

**Issue by yangxiu008** [mrkrd/matlab_wrapper#12]
sys info:
matlab 2010b 32 bit
python:2.7.9.0 32bit
matlab_wrapper 0.9.6

my problem:
it seems that libeng.dll in matlab can not be found.
here is my script:

Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import matlab_wrapper
  File "<stdin>", line 1
    port matlab_wrapper
                      ^
SyntaxError: invalid syntax
>>> import matlab_wrapper
>>> matlab=matlab_wrapper.MatlabSession()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win32\egg\matlab_wrapper\matlab_session.py", line 112, in __init__
  File "build\bdist.win32\egg\matlab_wrapper\matlab_session.py", line 308, in load_engine_and_libs
  File "build\bdist.win32\egg\matlab_wrapper\matlab_session.py", line 791, in __init__
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
>>> import sys
>>> sys.path.append('C:\Program Files (x86)\MATLAB\R2010bSP2\bin\win32')
>>> import ctypes
>>> ctypes.cdll.LoadLibrary('C:\Program Files (x86)\MATLAB\R2010bSP2\bin\win32\libeng.dll')
Exception AttributeError: "'MatlabSession' object has no attribute '_libeng'" in <bound method MatlabSession.__del__ of <MatlabSession:C:\Program Files (x86)\MATLAB\R2010bSP2\bin>> ignored
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
>>> import matlab_session
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named matlab_session
>>> sys.path.append('C:\Python27\Lib\site-packages\matlab_wrapper')
>>> import matlab_session
>>> matlab=matlab_wrapper.MatlabSession()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win32\egg\matlab_wrapper\matlab_session.py", line 112, in __init__
    engine, libeng, libmx, version = load_engine_and_libs(matlab_root, options)
  File "build\bdist.win32\egg\matlab_wrapper\matlab_session.py", line 308, in load_engine_and_libs
    libeng = Library('libeng')
  File "build\bdist.win32\egg\matlab_wrapper\matlab_session.py", line 791, in __init__
    self._lib = ctypes.CDLL(name, **kwargs)
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

**Comment by yangxiu008** [comment]
can any one help me? many thanks!!!

**Comment by yangxiu008** [comment]
matlab=matlab_wrapper.MatlabSession(options='-nosplash',matlab_root='C:\Program Files (x86)\MATLAB\R2010bSP2',)
>>> matlab.put('a',1)

after i add arguments(options='-nosplash',matlab_root='C:\Program Files (x86)\MATLAB\R2010bSP2'), no error. must I add these arguments?

**Comment by mrkrd** [comment]
I added some explanation to the FAQ:

https://github.com/mrkrd/matlab_wrapper/blob/master/FAQ.rst#error-unknown-matlab-location
