### ISSUE TITLE
not working for MATLAB 2015b, Mac OSX 10.10.5

### ISSUE THREAD

**Issue by rhoposit** [mrkrd/matlab_wrapper#21]
All tests pass. 

When I run eval_m_file.py:

```
Traceback (most recent call last):
  File "eval_m_file.py", line 25, in <module>
    main()
  File "eval_m_file.py", line 18, in main
    matlab.eval("run(my_script.m)")
  File "build/bdist.macosx-10.5-x86_64/egg/matlab_wrapper/matlab_session.py", line 177, in eval
  File "build/bdist.macosx-10.5-x86_64/egg/matlab_wrapper/matlab_session.py", line 241, in error_check
RuntimeError: MATLAB function <_FuncPtr object at 0x101f62c80> failed (<matlab_wrapper.matlab_session.LP_mxArray object at 0x101f84f80>) with arguments:
(<matlab_wrapper.matlab_session.LP_Engine object at 0x101f84dd0>, 'ERRSTR__')
```
Let me know what other info you need..

**Comment by mrkrd** [comment]
> Let me know what other info you need..

Could you check, if you can run my_script directly from Matlab when
Matlab is started in examples directory?

Do other example files work correctly?
