### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by MSA8D8** [mrkrd/matlab_wrapper#31]
I am faced with an unexpected error at the very beginning of this package.

The details of my environment are like this.
OS: Windows 10 64bit
Matlab R2014a
Python 3.6.0

whole source code I used is below
>import matlab_wrapper
matlab = matlab_wrapper.MatalbSession()

Here is the error message
> Traceback (most recent call last):
  File "D:\research\sasaki\Script\Python\windows\hello.py", line 2, in <module>
    matlab = matlab_wrapper.MatlabSession()
  File "C:\Users\CiNet\AppData\Roaming\Python\Python36\site-packages\matlab_wrapper\matlab_session.py", line 113, in __init__
    engine, libeng, libmx, version = load_engine_and_libs(matlab_root, options)
  File "C:\Users\CiNet\AppData\Roaming\Python\Python36\site-packages\matlab_wrapper\matlab_session.py", line 348, in load_engine_and_libs
    version = tuple([int(v) for v in version_str.split('.')[:2]])
TypeError: a bytes-like object is required, not 'str'

Thank you in advance

**Comment by mrkrd** [comment]
matlab_wrapper is for Python 2 only
